version: '3'
services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ../prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090

  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - 9100:9100

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - ../grafana:/var/lib/grafana